### ISSUE TITLE
make 'Koji Tag' a clickable link

### ISSUE THREAD

**Issue by crobinso** [release-engineering/mbs-ui#2]
I think it would be helpful to make the 'Koji Tag' field link directly to the koji web interface. Provides a clickable way to navigate from mbs web UI to all the builds that were requested in koji. For a tag named XXX you can use a URL like:

https://koji.fedoraproject.org/koji/search?match=exact&type=tag&terms=XXX

**Comment by mprahl** [comment]
Added in https://github.com/release-engineering/mbs-ui/commit/5a96c43a768971ea4f3793445155dc0841af0183 and https://github.com/release-engineering/mbs-ui/commit/5b726e02f7ecaf2a59646da868f31c5babde778e
